#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Main executable"""

import sys

from lib.gui.main import main
from lib.initialize import initialize


if __name__ == '__main__':
    initialize(sys.argv[0])
    main()
