#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Main executable"""

import gnome

from lib import APP_DIR
from lib.version import APP_NAME, APP_VERSION
from lib.gui.main import main


if __name__ == '__main__':
    gnome.program_init(APP_NAME.lower(), APP_VERSION, properties = { gnome.PARAM_APP_DATADIR : APP_DIR })
    main(APP_NAME, APP_VERSION)
